[2022-11-06T02:25:13.670+0200] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: udac_example_dag.Stage_songs scheduled__2019-01-12T00:00:00+00:00 [queued]>
[2022-11-06T02:25:13.676+0200] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: udac_example_dag.Stage_songs scheduled__2019-01-12T00:00:00+00:00 [queued]>
[2022-11-06T02:25:13.676+0200] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2022-11-06T02:25:13.676+0200] {taskinstance.py:1363} INFO - Starting attempt 3 of 4
[2022-11-06T02:25:13.676+0200] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2022-11-06T02:25:13.685+0200] {taskinstance.py:1383} INFO - Executing <Task(StageToRedshiftOperator): Stage_songs> on 2019-01-12 00:00:00+00:00
[2022-11-06T02:25:13.688+0200] {standard_task_runner.py:55} INFO - Started process 3477 to run task
[2022-11-06T02:25:13.693+0200] {standard_task_runner.py:82} INFO - Running: ['airflow', 'tasks', 'run', 'udac_example_dag', 'Stage_songs', 'scheduled__2019-01-12T00:00:00+00:00', '--job-id', '10', '--raw', '--subdir', 'DAGS_FOLDER/project/udac_example_dag.py', '--cfg-path', '/var/folders/sp/0_qfxj196m7gs6tyf69417g00000gn/T/tmp4rh6blr9']
[2022-11-06T02:25:13.695+0200] {standard_task_runner.py:83} INFO - Job 10: Subtask Stage_songs
[2022-11-06T02:25:13.738+0200] {task_command.py:376} INFO - Running <TaskInstance: udac_example_dag.Stage_songs scheduled__2019-01-12T00:00:00+00:00 [running]> on host mahmouds-macbook-pro.local
[2022-11-06T02:25:13.777+0200] {taskinstance.py:1590} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=udacity
AIRFLOW_CTX_DAG_ID=udac_example_dag
AIRFLOW_CTX_TASK_ID=Stage_songs
AIRFLOW_CTX_EXECUTION_DATE=2019-01-12T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=3
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2019-01-12T00:00:00+00:00
[2022-11-06T02:25:13.783+0200] {base.py:71} INFO - Using connection ID 'aws_credentials' for task execution.
[2022-11-06T02:25:13.783+0200] {connection_wrapper.py:303} INFO - AWS Connection (conn_id='aws_credentials', conn_type='aws') credentials retrieved from login and password.
[2022-11-06T02:25:13.795+0200] {stage_redshift.py:78} INFO - Clearing data destination Redshift table
[2022-11-06T02:25:13.799+0200] {base.py:71} INFO - Using connection ID 'redshift' for task execution.
[2022-11-06T02:25:13.800+0200] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/Users/mnagy99/airflow/plugins/operators/stage_redshift.py", line 79, in execute
    redshift_hook.run(f"TRUNCATE TABLE {self.table}") # Faster than DELETE FROM {self.table}
  File "/Users/mnagy99/opt/anaconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/providers/common/sql/hooks/sql.py", line 288, in run
    with closing(self.get_conn()) as conn:
  File "/Users/mnagy99/opt/anaconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/providers/postgres/hooks/postgres.py", line 115, in get_conn
    self.conn = psycopg2.connect(**conn_args)
  File "/Users/mnagy99/opt/anaconda3/envs/airflow-env/lib/python3.8/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: could not translate host name "redshift-cluster-1.cng0gslje4pq.us-west-2.redshift.amazonaws.com:5439/dev" to address: nodename nor servname provided, or not known

[2022-11-06T02:25:13.805+0200] {taskinstance.py:1401} INFO - Marking task as UP_FOR_RETRY. dag_id=udac_example_dag, task_id=Stage_songs, execution_date=20190112T000000, start_date=20221106T002513, end_date=20221106T002513
[2022-11-06T02:25:13.813+0200] {standard_task_runner.py:100} ERROR - Failed to execute job 10 for task Stage_songs (could not translate host name "redshift-cluster-1.cng0gslje4pq.us-west-2.redshift.amazonaws.com:5439/dev" to address: nodename nor servname provided, or not known
; 3477)
[2022-11-06T02:25:13.832+0200] {local_task_job.py:164} INFO - Task exited with return code 1
[2022-11-06T02:25:13.854+0200] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
