
ERROR:
------
psycopg2.errors.InternalError_: The specified S3 prefix 'log_data/2019/01/2019-01-12-events.json' does not exist

SOLUTION: 
----------
https://knowledge.udacity.com/questions/900408

'start_date': datetime(2018, 11, 1),


LOG:
----
*** Reading local file: /Users/mnagy99/airflow/logs/dag_id=udac_example_dag/run_id=scheduled__2019-01-12T07:00:00+00:00/task_id=Stage_events/attempt=2.log
[2022-11-07, 12:26:22 UTC] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: udac_example_dag.Stage_events scheduled__2019-01-12T07:00:00+00:00 [queued]>
[2022-11-07, 12:26:22 UTC] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: udac_example_dag.Stage_events scheduled__2019-01-12T07:00:00+00:00 [queued]>
[2022-11-07, 12:26:22 UTC] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2022-11-07, 12:26:22 UTC] {taskinstance.py:1363} INFO - Starting attempt 2 of 4
[2022-11-07, 12:26:22 UTC] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2022-11-07, 12:26:22 UTC] {taskinstance.py:1383} INFO - Executing <Task(StageToRedshiftOperator): Stage_events> on 2019-01-12 07:00:00+00:00
[2022-11-07, 12:26:22 UTC] {standard_task_runner.py:55} INFO - Started process 1706 to run task
[2022-11-07, 12:26:22 UTC] {standard_task_runner.py:82} INFO - Running: ['airflow', 'tasks', 'run', 'udac_example_dag', 'Stage_events', 'scheduled__2019-01-12T07:00:00+00:00', '--job-id', '67', '--raw', '--subdir', 'DAGS_FOLDER/project/udac_example_dag.py', '--cfg-path', '/var/folders/sp/0_qfxj196m7gs6tyf69417g00000gn/T/tmpd3ma3ry1']
[2022-11-07, 12:26:22 UTC] {standard_task_runner.py:83} INFO - Job 67: Subtask Stage_events
[2022-11-07, 12:26:22 UTC] {task_command.py:376} INFO - Running <TaskInstance: udac_example_dag.Stage_events scheduled__2019-01-12T07:00:00+00:00 [running]> on host mahmouds-macbook-pro.local
[2022-11-07, 12:26:23 UTC] {logging_mixin.py:120} WARNING - /Users/mnagy99/opt/anaconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/utils/context.py:204 AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
[2022-11-07, 12:26:23 UTC] {taskinstance.py:1590} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=udacity
AIRFLOW_CTX_DAG_ID=udac_example_dag
AIRFLOW_CTX_TASK_ID=Stage_events
AIRFLOW_CTX_EXECUTION_DATE=2019-01-12T07:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2019-01-12T07:00:00+00:00
[2022-11-07, 12:26:23 UTC] {base.py:71} INFO - Using connection ID 'aws_credentials' for task execution.
[2022-11-07, 12:26:23 UTC] {connection_wrapper.py:303} INFO - AWS Connection (conn_id='aws_credentials', conn_type='aws') credentials retrieved from login and password.
[2022-11-07, 12:26:23 UTC] {stage_redshift.py:115} INFO - Clearing data destination Redshift table
[2022-11-07, 12:26:23 UTC] {base.py:71} INFO - Using connection ID 'redshift' for task execution.
[2022-11-07, 12:26:26 UTC] {sql.py:315} INFO - Running statement: TRUNCATE TABLE staging_events, parameters: None
[2022-11-07, 12:26:27 UTC] {stage_redshift.py:122} INFO - Copying data from s3 to Redshift
[2022-11-07, 12:26:27 UTC] {logging_mixin.py:120} WARNING - /Users/mnagy99/opt/anaconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/utils/context.py:204 AirflowContextDeprecationWarning: Accessing 'next_ds' from the template is deprecated and will be removed in a future version. Please use '{{ data_interval_end | ds }}' instead.
[2022-11-07, 12:26:27 UTC] {logging_mixin.py:120} WARNING - /Users/mnagy99/opt/anaconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/utils/context.py:204 AirflowContextDeprecationWarning: Accessing 'next_ds_nodash' from the template is deprecated and will be removed in a future version. Please use '{{ data_interval_end | ds_nodash }}' instead.
[2022-11-07, 12:26:27 UTC] {logging_mixin.py:120} WARNING - /Users/mnagy99/opt/anaconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/utils/context.py:204 AirflowContextDeprecationWarning: Accessing 'next_execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_end' instead.
[2022-11-07, 12:26:27 UTC] {logging_mixin.py:120} WARNING - /Users/mnagy99/opt/anaconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/utils/context.py:204 AirflowContextDeprecationWarning: Accessing 'prev_ds' from the template is deprecated and will be removed in a future version.
[2022-11-07, 12:26:27 UTC] {logging_mixin.py:120} WARNING - /Users/mnagy99/opt/anaconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/utils/context.py:204 AirflowContextDeprecationWarning: Accessing 'prev_ds_nodash' from the template is deprecated and will be removed in a future version.
[2022-11-07, 12:26:27 UTC] {logging_mixin.py:120} WARNING - /Users/mnagy99/opt/anaconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/utils/context.py:204 AirflowContextDeprecationWarning: Accessing 'prev_execution_date' from the template is deprecated and will be removed in a future version.
[2022-11-07, 12:26:27 UTC] {logging_mixin.py:120} WARNING - /Users/mnagy99/opt/anaconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/utils/context.py:204 AirflowContextDeprecationWarning: Accessing 'prev_execution_date_success' from the template is deprecated and will be removed in a future version. Please use 'prev_data_interval_start_success' instead.
[2022-11-07, 12:26:27 UTC] {logging_mixin.py:120} WARNING - /Users/mnagy99/opt/anaconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/utils/context.py:204 AirflowContextDeprecationWarning: Accessing 'tomorrow_ds' from the template is deprecated and will be removed in a future version.
[2022-11-07, 12:26:27 UTC] {logging_mixin.py:120} WARNING - /Users/mnagy99/opt/anaconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/utils/context.py:204 AirflowContextDeprecationWarning: Accessing 'tomorrow_ds_nodash' from the template is deprecated and will be removed in a future version.
[2022-11-07, 12:26:27 UTC] {logging_mixin.py:120} WARNING - /Users/mnagy99/opt/anaconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/utils/context.py:204 AirflowContextDeprecationWarning: Accessing 'yesterday_ds' from the template is deprecated and will be removed in a future version.
[2022-11-07, 12:26:27 UTC] {logging_mixin.py:120} WARNING - /Users/mnagy99/opt/anaconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/utils/context.py:204 AirflowContextDeprecationWarning: Accessing 'yesterday_ds_nodash' from the template is deprecated and will be removed in a future version.
[2022-11-07, 12:26:27 UTC] {base.py:71} INFO - Using connection ID 'redshift' for task execution.
[2022-11-07, 12:26:30 UTC] {sql.py:315} INFO - Running statement: 
        COPY staging_events
        FROM 's3://udacity-dend/log_data/2019/01/2019-01-12-events.json'
        ACCESS_KEY_ID 'AKIAQG756CCNWGODFBM6'
        SECRET_ACCESS_KEY '***'
        JSON 'auto'
    , parameters: None
[2022-11-07, 12:26:30 UTC] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/Users/mnagy99/airflow/plugins/operators/stage_redshift.py", line 134, in execute
    redshift_hook.run(formatted_sql)
  File "/Users/mnagy99/opt/anaconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/providers/common/sql/hooks/sql.py", line 295, in run
    self._run_command(cur, sql_statement, parameters)
  File "/Users/mnagy99/opt/anaconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/providers/common/sql/hooks/sql.py", line 320, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.InternalError_: The specified S3 prefix 'log_data/2019/01/2019-01-12-events.json' does not exist
DETAIL:  
  -----------------------------------------------
  error:  The specified S3 prefix 'log_data/2019/01/2019-01-12-events.json' does not exist
  code:      8001
  context:   
  query:     200035
  location:  s3_utility.cpp:694
  process:   padbmaster [pid=18710]
  -----------------------------------------------


[2022-11-07, 12:26:30 UTC] {taskinstance.py:1401} INFO - Marking task as UP_FOR_RETRY. dag_id=udac_example_dag, task_id=Stage_events, execution_date=20190112T070000, start_date=20221107T122622, end_date=20221107T122630
[2022-11-07, 12:26:30 UTC] {standard_task_runner.py:100} ERROR - Failed to execute job 67 for task Stage_events (The specified S3 prefix 'log_data/2019/01/2019-01-12-events.json' does not exist
DETAIL:  
  -----------------------------------------------
  error:  The specified S3 prefix 'log_data/2019/01/2019-01-12-events.json' does not exist
  code:      8001
  context:   
  query:     200035
  location:  s3_utility.cpp:694
  process:   padbmaster [pid=18710]
  -----------------------------------------------

; 1706)
[2022-11-07, 12:26:30 UTC] {local_task_job.py:164} INFO - Task exited with return code 1
[2022-11-07, 12:26:31 UTC] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
